import type { Metadata } from "next";
import { Geist, Geist_Mono, Inter, Poppins } from "next/font/google";
import "./globals.css";
import Header from "@/components/HeaderFooter/Header";
import CustomCursor from "@/components/GsapComponents/CustomCursor";
import GsapFadeUpOnLoad from "@/components/GsapComponents/FadeupHandlerForSingle";
import LenisWrapper from "@/components/SmoothScroll/LenisWrapper";
import Footer from "@/components/HeaderFooter/Footer";
// import MaskedTextSwap from "@/components/GsapComponents/MaskTextReveal";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-geist-inter",
});

const poppins = Poppins({
  weight: ["300", "400", "500", "600", "700", "800", "900"],
  subsets: ["latin"],
  variable: "--font-geist-poppins",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable}  antialiased overflow-x-hidden`}
      >
        <LenisWrapper>
          <CustomCursor />
          <GsapFadeUpOnLoad />
          <Header />

          {/* <MaskedTextSwap /> */}
          {children}
          <Footer />
        </LenisWrapper>
      </body>
    </html>
  );
}
